################################
# API Manager
autodiscoveryId: "20839571"

# Listener
https:
  port: "443"
################################

protocol: "HTTPS"

database:
  host: "sys-database-5bg6zk.5sc6y6-4.usa-e2.cloudhub.io"
  port: "443"
  base-path: "/api/v1"
  client-id: "1fdb8467e8f64fb896b5600b22187568"
  client-secret: "F0962F1f52c445dFbA8589aE61e5A4c4"
  
sftp:
  host: "sys-sftp-5bg6zk.5sc6y6-3.usa-e2.cloudhub.io"
  port: "443"
  base-path: "/api/v1"
  client-id: "1fdb8467e8f64fb896b5600b22187568"
  client-secret: "F0962F1f52c445dFbA8589aE61e5A4c4"