################################
# API Manager
autodiscoveryId: "000000"

# Listener
https:
  port: "443"
################################

protocol: "HTTPS"

database:
  host: ""
  port: "443"
  client-id: ""
  client-secret: ""
  
sftp:
  host: ""
  port: "443"
  client-id: ""
  client-secret: ""